@URL = http://localhost:3000/api/users
@tokenN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODhlM2Y4YmI4YTc3NjNlZWNlYzk4ZDUiLCJpc0FkbWluIjpmYWxzZSwic3Vic2NyaXB0aW9uUGxhbiI6ImZyZWUiLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvZm5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NTQxNzMxNjksImV4cCI6MTc1NDc3Nzk2OX0.VziHpZ7gsdmPiJ_JNbib7YPQyxe1uxumVMfzJhtTGYg
@tokenA = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODhlNDUyODY2YzRlMjM2YzNmZDhjNWYiLCJpc0FkbWluIjp0cnVlLCJzdWJzY3JpcHRpb25QbGFuIjoiZnJlZSIsIm5hbWUiOiJPciBIYWtsYXkiLCJlbWFpbCI6Im9yLmhha2xheUBnbWFpbC5jb20iLCJpYXQiOjE3NTQxNzI5MTksImV4cCI6MTc1NDc3NzcxOX0.foHx6mH4K0OnUKbvGviuxFxUg37AQZo8gekFRZ34B7o

### Get all users
GET {{URL}}
authorization: {{tokenA}}

### Get all users with pagination and sorting
GET {{URL}}?limit=2&sort=name

### Get user by ID
GET {{URL}}/688e3f8bb8a7763eecec98d5

### Create a new user
POST {{URL}}
Content-Type: application/json

{
  "name": "Or Haklay",
  "email": "or.haklay@gmail.com",
  "password": "Password123"
}
### login user
POST {{URL}}/login
Content-Type: application/json

{
  "email": "jofn@example.com",
  "password": "Password123"
}

### Update user by ID
PUT {{URL}}/688e41c067b05cd819584dbc
Content-Type: application/json
authorization: {{tokenN}}

{
  "name": "John Doe Updated"
}

### Delete user by ID
DELETE {{URL}}/688e41c067b05cd819584dbc
authorization: {{tokenA}}
